/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 6.0.0   2016-10-10

 The MIT License (MIT)
 Copyright (c) 2009-2016 Atollic AB

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 ******************************************************************************
 */

/* Includes */
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include "stm32l1xx.h"
#include "vrs_cv5.h"
#include <math.h>

/* Private typedef */
/* Private define  */
/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */
volatile int AD_value,AD_value1, pomocna2 = 1;
volatile int odosli=0, a=0, pocznakov=0;
volatile char buffer[50];

void USART2_IRQHandler(void) {
	uint8_t pom = 0;
	if (USART_GetITStatus(USART2, USART_IT_TC) != RESET)
	{
		USART_ClearITPendingBit(USART2, USART_IT_TC);  // nulujem flag prerusenia ktory uz nastal

		if(a<pocznakov && pocznakov<50){
			USART_SendData(USART2, buffer[a]);
			a++;
		}
		else{
			a = 0;
			pocznakov=0;
		}




	}

	if (USART_GetITStatus(USART2, USART_IT_RXNE) != RESET) {
		USART_ClearITPendingBit(USART2, USART_IT_RXNE);
		pom = USART_ReceiveData(USART2);
		if (pom == 'm') {
			if (pomocna2 != 2) {
				pomocna2 = 2;
			} else {
				pomocna2 = 1;
			}
		}
	}
}

void ADC1_IRQHandler(void) {
	if (ADC1->SR & ADC_SR_EOC) {
		AD_value1 = ADC1->DR;
	/*	if(pomocna2==2){
			AD_value=(3.3*AD_value1*10)/4096;

		}
		else{
			AD_value=AD_value1;
		}
		//USART_SendData(USART2, 's');*/
	}
}

int main(void) {

	char c[5];
	int alfa;

	adc_init();
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_4);
	NVIC_InitTypeDef NVIC_InitStructure;
	NVIC_InitStructure.NVIC_IRQChannel = USART2_IRQn; /// seriovy
	NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 1;
	NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0;
	NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
	NVIC_Init(&NVIC_InitStructure);

	NVIC_InitStructure.NVIC_IRQChannel = ADC1_IRQn;
	NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 0;
	NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0;
	NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
	NVIC_Init(&NVIC_InitStructure);

	GPIO_InitTypeDef GPIO_InitStructure;
	RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOA, ENABLE);
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_40MHz;
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_5;
	GPIO_Init(GPIOA, &GPIO_InitStructure);
	// povolime prerusenia pre ADC
	ADC_ITConfig(ADC1, ADC_IT_EOC, ENABLE);

	int i = 0;

	/* adc_init();
	 ADC_SoftwareStartConv(ADC1);
	 while(!ADC_GetFlagStatus(ADC1, ADC_FLAG_EOC)){}
	 int AD_value=ADC_GetConversionValue(ADC1);*/

	//PutcUART2(AD_value);
	/* Infinite loop */
//	while (1) {
		/* Start ADC Software Conversion
		 ADC_SoftwareStartConv(ADC1);
		 while(!ADC_GetFlagStatus(ADC1, ADC_FLAG_EOC)){}
		 AD_value=ADC_GetConversionValue(ADC1);*/
	while(1){
		if(pomocna2==2){
					AD_value=(3.3*AD_value1)/4096;

				}
				else{
					AD_value=AD_value1;
				}
	    sprintf(c, "%d\n", AD_value);
	    for(int b=0;b<=30000;b++);
	    if(pocznakov==0){
	    	USART_SendData(USART2, c[0]);
	    	for(i=1;i<6;i++){
	    		       buffer[pocznakov]=c[i];
	    		       pocznakov++;
	    		       }
	    		}
	    else{
	     for(i=0;i<6;i++){
	       buffer[pocznakov]=c[i];
	       pocznakov++;
	       }
	    }
	    }

		GPIO_SetBits(GPIOA, GPIO_Pin_5);
		for (i = 0; i < AD_value * 100; i++);
		GPIO_ResetBits(GPIOA, GPIO_Pin_5);
		for (i = 0; i < AD_value * 100; i++);
		// stlacili sme 'm' ?





//	}
	return 0;
}

#ifdef  USE_FULL_ASSERT

/**
 * @brief  Reports the name of the source file and the source line number
 *   where the assert_param error has occurred.
 * @param  file: pointer to the source file name
 * @param  line: assert_param error line source number
 * @retval None
 */
void assert_failed(uint8_t* file, uint32_t line)
{
	/* User can add his own implementation to report the file name and line number,
	 ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

	/* Infinite loop */
	while (1)
	{
	}
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func,
		const char *failedexpr) {
	while (1) {
	}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr) {
	__assert_func(file, line, NULL, failedexpr);
}
